version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile.frontend
      context: .
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      dockerfile: Dockerfile.backend
      context: .
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

networks:
  app-network:
    driver: bridge